name: "CI (Integração Continua): Main Workflow"
on:
  pull_request:
    types: [opened,synchronize]  
# Definindo o que queremos executar    
jobs:
  linter:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: npm install -y
      - name: Run Linter
        run: npm run lint   