name: "CI (Integração Continua): Primeira Action"
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']  
# Definindo o que queremos executar    
jobs:
    exemplo:  
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run a one-line script
              run: echo Hello, world!        